version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: spring-app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - backend-network

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
