package com.valanse.valanse.service.PurgeService;

import com.valanse.valanse.domain.Member;
import com.valanse.valanse.repository.MemberRepository;
import com.valanse.valanse.service.StorageService.StorageService;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;

import java.sql.Timestamp;
import java.time.LocalDateTime;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.verifyNoInteractions;

@SpringBootTest
@ActiveProfiles("test")
class SoftDeletePurgeRollbackIntegrationTest {
    @Autowired private SoftDeletePurgeService purgeService;
    @Autowired private MemberRepository memberRepository;
    @Autowired private JdbcTemplate jdbcTemplate;
    @MockBean private StorageService storageService;

    private Long memberId;

    @BeforeEach
    void setUp() {
        jdbcTemplate.execute("drop table if exists purge_member_guard");
        jdbcTemplate.update("delete from storage_delete_task");

        Member member = memberRepository.save(Member.builder()
                .socialId("rollback-" + System.nanoTime())
                .email("rollback@example.com")
                .name("롤백 테스트")
                .build());
        memberId = member.getId();
        jdbcTemplate.update("""
                        update member
                        set deleted_at = ?, profile_image_url = ?
                        where id = ?
                        """,
                Timestamp.valueOf(LocalDateTime.now().minusDays(15)),
                "https://cdn.example.com/rollback.png",
                memberId);
        jdbcTemplate.execute("""
                create table purge_member_guard (
                    id bigint generated by default as identity primary key,
                    member_id bigint not null,
                    constraint fk_purge_member_guard
                        foreign key (member_id) references member(id)
                )
                """);
        jdbcTemplate.update("insert into purge_member_guard (member_id) values (?)", memberId);
    }

    @AfterEach
    void tearDown() {
        jdbcTemplate.execute("drop table if exists purge_member_guard");
        if (memberId != null) {
            jdbcTemplate.update("delete from member where id = ?", memberId);
        }
        jdbcTemplate.update("delete from storage_delete_task");
    }

    @Test
    void databaseFailureRollsBackBothDomainDeletionAndOutboxInsertion() {
        assertThatThrownBy(() -> purgeService.purgeExpired(LocalDateTime.now()))
                .isInstanceOf(DataIntegrityViolationException.class);

        assertThat(jdbcTemplate.queryForObject(
                "select count(*) from member where id = ?",
                Integer.class,
                memberId)).isEqualTo(1);
        assertThat(jdbcTemplate.queryForObject(
                "select count(*) from storage_delete_task",
                Integer.class)).isZero();
        verifyNoInteractions(storageService);
    }
}
